(TeX-add-style-hook
 "gm-termtest-C-mock"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "11pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("xcolor" "table")))
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art11"
    "enumerate"
    "syllogism"
    "october"
    "xcolor")
   (LaTeX-add-labels
    "eq:ohdiedoe"
    "eq:mahbeizo"
    "eq:ohwoojie"
    "eq:chohtohk"
    "eq:gofushoo"
    "eq:vibeibie"
    "eq:aepheipi"
    "eq:vogeobab"
    "eq:uxohjeib"
    "eq:eicohrae"
    "eq:epuufeca"
    "eq:weungodu"
    "eq:oraighah"
    "eq:saenonge"
    "eq:eeghoghi"
    "eq:eesicaet"
    "eq:fixahfee"
    "eq:iesiwoox"
    "eq:ezaishoo"
    "eq:eemengaj"
    "eq:faeyeije"
    "eq:ochedoxi"
    "eq:veipoeyu"
    "eq:aquusahm"
    "eq:rohkiine"
    "eq:zahsuini"
    "eq:iaphaeya"
    "eq:iebaiviu"
    "eq:maareiju"
    "eq:sheuroov"
    "eq:dairithe"
    "eq:seizieng"
    "eq:ceivapuw"
    "eq:eefohvoh"
    "eq:xiefepib"
    "eq:eegaifah"
    "eq:phahmobu"
    "eq:xonguoge"
    "eq:aeshaite"
    "eq:eequabae"
    "eq:niephait"
    "eq:eophooki"
    "eq:eevaicei"
    "eq:ohquaiva"
    "eq:poikeeng"
    "eq:haesiiro"
    "eq:quahphia"
    "eq:iemahbec"))
 :latex)

